"""add separate cvss_v2 and cvss_v3 tables with abstract base

Revision ID: d2706dbc2387
Revises: 8db71ab731b2
Create Date: 2026-01-15 14:56:30.874712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2706dbc2387"
down_revision: Union[str, Sequence[str], None] = "8db71ab731b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cvss_v2",
        sa.Column("access_vector", sa.String(length=30), nullable=True),
        sa.Column("access_complexity", sa.String(length=30), nullable=True),
        sa.Column("authentication", sa.String(length=30), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=30), nullable=True),
        sa.Column("integrity_impact", sa.String(length=30), nullable=True),
        sa.Column("availability_impact", sa.String(length=30), nullable=True),
        sa.Column("ac_insuf_info", sa.Boolean(), nullable=True),
        sa.Column("obtain_all_privilege", sa.Boolean(), nullable=True),
        sa.Column("obtain_user_privilege", sa.Boolean(), nullable=True),
        sa.Column("obtain_other_privilege", sa.Boolean(), nullable=True),
        sa.Column("user_interaction_required", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.String(), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("base_score", sa.Float(), nullable=True),
        sa.Column("base_severity", sa.String(length=20), nullable=True),
        sa.Column("vector_string", sa.String(length=150), nullable=True),
        sa.Column("exploitability_score", sa.Float(), nullable=True),
        sa.Column("impact_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cves.cve_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cve_id", name="uq_cvss_v2_cve"),
    )
    op.create_index(
        op.f("ix_cvss_v2_base_severity"), "cvss_v2", ["base_severity"], unique=False
    )
    op.create_index(op.f("ix_cvss_v2_cve_id"), "cvss_v2", ["cve_id"], unique=True)
    op.create_table(
        "cvss_v3",
        sa.Column("attack_vector", sa.String(length=30), nullable=True),
        sa.Column("attack_complexity", sa.String(length=30), nullable=True),
        sa.Column("privileges_required", sa.String(length=30), nullable=True),
        sa.Column("user_interaction", sa.String(length=30), nullable=True),
        sa.Column("scope", sa.String(length=20), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=30), nullable=True),
        sa.Column("integrity_impact", sa.String(length=30), nullable=True),
        sa.Column("availability_impact", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.String(), nullable=False),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("base_score", sa.Float(), nullable=True),
        sa.Column("base_severity", sa.String(length=20), nullable=True),
        sa.Column("vector_string", sa.String(length=150), nullable=True),
        sa.Column("exploitability_score", sa.Float(), nullable=True),
        sa.Column("impact_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["cve_id"], ["cves.cve_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cve_id", name="uq_cvss_v3_cve"),
    )
    op.create_index(
        op.f("ix_cvss_v3_base_severity"), "cvss_v3", ["base_severity"], unique=False
    )
    op.create_index(op.f("ix_cvss_v3_cve_id"), "cvss_v3", ["cve_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cvss_v3_cve_id"), table_name="cvss_v3")
    op.drop_index(op.f("ix_cvss_v3_base_severity"), table_name="cvss_v3")
    op.drop_table("cvss_v3")
    op.drop_index(op.f("ix_cvss_v2_cve_id"), table_name="cvss_v2")
    op.drop_index(op.f("ix_cvss_v2_base_severity"), table_name="cvss_v2")
    op.drop_table("cvss_v2")
    # ### end Alembic commands ###
