"""add one unique constraints on vulnerable_versions

Revision ID: 4d3051be4f79
Revises: b04c8329fb77
Create Date: 2026-02-22 08:29:15.327562

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4d3051be4f79"
down_revision: Union[str, Sequence[str], None] = "b04c8329fb77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_fixed_version_per_package"), "vulnerable_versions", type_="unique"
    )
    op.drop_constraint(
        op.f("uq_range_start_end_per_package"), "vulnerable_versions", type_="unique"
    )
    op.create_unique_constraint(
        "uq_version_range_per_package",
        "vulnerable_versions",
        [
            "package_id",
            "fixed_version",
            "including_version_start",
            "excluding_version_end",
            "including_version_end",
            "operator",
            "negate",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_version_range_per_package", "vulnerable_versions", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_range_start_end_per_package"),
        "vulnerable_versions",
        ["package_id", "including_version_start", "excluding_version_end", "operator"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_fixed_version_per_package"),
        "vulnerable_versions",
        ["package_id", "fixed_version"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
