"""add unique constraints on vulnerable_versions

Revision ID: b04c8329fb77
Revises: 0586dd4e7de9
Create Date: 2026-02-22 08:16:17.832044

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b04c8329fb77"
down_revision: Union[str, Sequence[str], None] = "0586dd4e7de9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_version_package_id", "vulnerable_versions", ["package_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_fixed_version_per_package",
        "vulnerable_versions",
        ["package_id", "fixed_version"],
    )
    op.create_unique_constraint(
        "uq_range_start_end_per_package",
        "vulnerable_versions",
        ["package_id", "including_version_start", "excluding_version_end", "operator"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_range_start_end_per_package", "vulnerable_versions", type_="unique"
    )
    op.drop_constraint(
        "uq_fixed_version_per_package", "vulnerable_versions", type_="unique"
    )
    op.drop_index("ix_version_package_id", table_name="vulnerable_versions")
    # ### end Alembic commands ###
