"""add unique constraints for upsert safety

Revision ID: 0586dd4e7de9
Revises: c6615e14026e
Create Date: 2026-02-22 05:37:14.227040

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0586dd4e7de9"
down_revision: Union[str, Sequence[str], None] = "c6615e14026e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_vulnerable_package_cve_cpe", "vulnerable_packages", ["cve_id", "cpe_string"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_vulnerable_package_cve_cpe", "vulnerable_packages", type_="unique"
    )
    # ### end Alembic commands ###
