"""initial schema - CVE + VulnerablePackage + Ranges

Revision ID: 889166b03cf8
Revises:
Create Date: 2026-01-10 22:45:40.031402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "889166b03cf8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cves",
        sa.Column("cve_id", sa.String(), nullable=False),
        sa.Column("published", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("vuln_status", sa.String(length=70), nullable=True),
        sa.PrimaryKeyConstraint("cve_id"),
    )
    op.create_table(
        "vulnerable_packages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("package_name", sa.String(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=True),
        sa.Column("cpe_string", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["cve_id"], ["cves.cve_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_ecosystem_package",
        "vulnerable_packages",
        ["vendor", "package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerable_packages_category"),
        "vulnerable_packages",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerable_packages_package_name"),
        "vulnerable_packages",
        ["package_name"],
        unique=False,
    )
    op.create_table(
        "vulnerable_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("package_id", sa.Integer(), nullable=False),
        sa.Column("fixed_version", sa.String(length=100), nullable=True),
        sa.Column("including_version_start", sa.String(length=100), nullable=True),
        sa.Column("excluding_version_end", sa.String(length=100), nullable=True),
        sa.Column("including_version_end", sa.String(length=100), nullable=True),
        sa.Column("operator", sa.String(length=100), nullable=True),
        sa.Column("negate", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["package_id"], ["vulnerable_packages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vulnerable_versions")
    op.drop_index(
        op.f("ix_vulnerable_packages_package_name"), table_name="vulnerable_packages"
    )
    op.drop_index(
        op.f("ix_vulnerable_packages_category"), table_name="vulnerable_packages"
    )
    op.drop_index("idx_ecosystem_package", table_name="vulnerable_packages")
    op.drop_table("vulnerable_packages")
    op.drop_table("cves")
    # ### end Alembic commands ###
