"""add source to CVE + version improvements + indexes

Revision ID: 8db71ab731b2
Revises: 6b6b76d3e961
Create Date: 2026-01-12 20:44:47.477672

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8db71ab731b2"
down_revision: Union[str, Sequence[str], None] = "6b6b76d3e961"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_ecosystem_package"), table_name="vulnerable_packages")
    op.create_index(
        "idx_vendor_package",
        "vulnerable_packages",
        ["vendor_id", "package_name"],
        unique=False,
    )
    op.create_index("ix_package_cve", "vulnerable_packages", ["cve_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_package_cve", table_name="vulnerable_packages")
    op.drop_index("idx_vendor_package", table_name="vulnerable_packages")
    op.create_index(
        op.f("idx_ecosystem_package"),
        "vulnerable_packages",
        ["vendor_id", "package_name"],
        unique=False,
    )
    # ### end Alembic commands ###
