"""removed version column from CVSSBase model

Revision ID: c6615e14026e
Revises: e6e74f534873
Create Date: 2026-01-17 08:42:53.000508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6615e14026e"
down_revision: Union[str, Sequence[str], None] = "e6e74f534873"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cvss_v2", "version")
    op.drop_index(op.f("ix_cvss_v3_base_severity"), table_name="cvss_v31")
    op.drop_index(op.f("ix_cvss_v3_cve_id"), table_name="cvss_v31")
    op.drop_constraint(op.f("uq_cvss_v3_cve"), "cvss_v31", type_="unique")
    op.create_index(
        op.f("ix_cvss_v31_base_severity"), "cvss_v31", ["base_severity"], unique=False
    )
    op.create_index(op.f("ix_cvss_v31_cve_id"), "cvss_v31", ["cve_id"], unique=True)
    op.create_unique_constraint("uq_cvss_v31_cve", "cvss_v31", ["cve_id"])
    op.drop_column("cvss_v31", "version")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cvss_v31",
        sa.Column(
            "version", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint("uq_cvss_v31_cve", "cvss_v31", type_="unique")
    op.drop_index(op.f("ix_cvss_v31_cve_id"), table_name="cvss_v31")
    op.drop_index(op.f("ix_cvss_v31_base_severity"), table_name="cvss_v31")
    op.create_unique_constraint(
        op.f("uq_cvss_v3_cve"),
        "cvss_v31",
        ["cve_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_cvss_v3_cve_id"), "cvss_v31", ["cve_id"], unique=True)
    op.create_index(
        op.f("ix_cvss_v3_base_severity"), "cvss_v31", ["base_severity"], unique=False
    )
    op.add_column(
        "cvss_v2",
        sa.Column(
            "version", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
