"""add Vendor model and table

Revision ID: 6b6b76d3e961
Revises: 889166b03cf8
Create Date: 2026-01-12 13:45:12.479416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b6b76d3e961"
down_revision: Union[str, Sequence[str], None] = "889166b03cf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("cves", sa.Column("source", sa.String(), nullable=True))
    op.add_column(
        "vulnerable_packages", sa.Column("vendor_id", sa.Integer(), nullable=True)
    )
    op.drop_index(op.f("idx_ecosystem_package"), table_name="vulnerable_packages")
    op.create_index(
        "idx_ecosystem_package",
        "vulnerable_packages",
        ["vendor_id", "package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vulnerable_packages_vendor_id"),
        "vulnerable_packages",
        ["vendor_id"],
        unique=False,
    )
    op.create_foreign_key(None, "vulnerable_packages", "vendors", ["vendor_id"], ["id"])
    op.drop_column("vulnerable_packages", "vendor")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vulnerable_packages",
        sa.Column("vendor", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "vulnerable_packages", type_="foreignkey")
    op.drop_index(
        op.f("ix_vulnerable_packages_vendor_id"), table_name="vulnerable_packages"
    )
    op.drop_index("idx_ecosystem_package", table_name="vulnerable_packages")
    op.create_index(
        op.f("idx_ecosystem_package"),
        "vulnerable_packages",
        ["vendor", "package_name"],
        unique=False,
    )
    op.drop_column("vulnerable_packages", "vendor_id")
    op.drop_column("cves", "source")
    op.drop_table("vendors")
    # ### end Alembic commands ###
